### ISSUE TITLE
Need a "Getting Started with ScribeUI"

### ISSUE THREAD

**Issue by dmorissette** [mapgears/scribeui#109]
The "Getting Started with ScribeUI" page on scribeui.org only contains installation instructions, but that's just one piece of the puzzle.

We need a document that shows the users how to use the software, introducing the key concepts and with screen shots showing how to use each of the key features.

Start with the minimum for anyone to be able to create/edit a map:

- Create your first workspace
- Create your first map (choose a map type, template, etc.)
- Introduce the three tabs (Manager, Editor, Browse) and their resepective roles
- Overview of the Editor tab and how to use its basic options to make changes to a map

And then in a second phase add more advanced topics:

- Advanced Editor tools
- Using log/debug tools
- Using bookmarks/shortcuts to zoom to specific region
- Creating tile caches
- Importing/exporting maps (is that supported yet?)
- Using the Browse tools to upload/manage data

**Comment by samuellapointe** [comment]
I created the first part of the Getting Started guide: https://github.com/mapgears/scribeui/wiki/Getting-started-with-ScribeUI

I will write the more advanced parts later this summer, when they're all working

**Comment by dmorissette** [comment]
I love it! Thanks!

**Comment by dmorissette** [comment]
Actually, we'd need a link to the Getting Started guide in the main scribejui.org website at:
http://scribeui.org/getting-started.html

The current contents of this page is actually installation instructions, so perhaps we could move the contents of the page to a separate installaiton page, and that getting-started.html could contain links to both the new Getting Started in the wiki, and the installation instructions. When we have more docs we can link them from there as well.

**Comment by jlap** [comment]
Indeed, I suggest you keep the images hosted on github if you can, then you should be able to copy paste the markdown source of your wiki page to a new page of the website. 

I don't think I left instructions about that website but it is pretty simple. It is a Jekyll website hosted on github pages. From your scribeui repo, git clone the gh-pages branch and you will be able to make your modifications. More detailed information about this here:https://help.github.com/articles/using-jekyll-with-pages/


You can either reopen the current issue or create a new ticket.
