### ISSUE TITLE
local.ini needs an option for the cgi-bin url

### ISSUE THREAD

**Issue by Knuk** [mapgears/scribeui#112]
By default, ScribeUI looks for the cgi-bin folder on http://localhost:port/cgi-bin/proxy.cgi. The local.ini file needs an option to set the url to the cgi-bin folder.

**Comment by Knuk** [comment]
Fixed in 66780714042c6791bc4bc1bbb7b310c8353bb48e

**Comment by samuellapointe** [comment]
To do this, I replaced the $WSNAME javascript global variable by a $SETTINGS global object containing the wsname and cgibin_url attributes. The MainView class in scribeui_pyramid/modules/main/views.py no longer returns 'workspace'. Instead, it returns the settings in json and regular format.
