### ISSUE TITLE
fail on ":" character

### ISSUE THREAD

**Issue by smercier** [mapgears/scribeui#113]
Scribe fail on ":" character.

```
WEB {
        METADATA {{
            "ows_enable_request"   "*"
            "wms_srs"   "EPSG:900913 EPSG:4326 EPSG:3857"
            "labelcache_map_edge_buffer"   "10"
            "wms_title"   "grid"
        "wms_onlineresource"    "http://mapserver.com:8081/cgi-bin/mapserv?map=/opt/scribeui/workspaces/blabla.map"    
        }}
        IMAGEPATH: '/tmp/ms_tmp/'
        IMAGEURL: '/ms_tmp/'
    }
```
give error:

```
[Tue May 19 21:04:06 2015].231654 getString(): Symbol definition error. Parsing error near (:):(line 20)
```
but this work:
```
"wms_onlineresource"    "mapserver.com/cgi-bin/mapserv?map=/opt/scribeui/workspaces/blabla.map"   
```

**Comment by dmorissette** [comment]
To help troubleshoot this, I suggest that whoever works on this look at the output of scribe.py on that mapfile fragment. It is very likely that the scribe.py script truncates the string at the ":" which results in an invalid mapfile as output.

The solution would likely be to have the scribe.py parser honor strings when it looks for ":".

**Comment by samuellapointe** [comment]
The problem comes from Scribe removing comments, so anything starting with //. I am working on a fix right now.
