### ISSUE TITLE
Add new features from this summer to the Getting Started wiki page

### ISSUE THREAD

**Issue by jlap** [mapgears/scribeui#140]
This last summer of code was great, a lot of new features emerged ! @samuellapointe one of the first things you did was the [Getting Started](https://github.com/mapgears/scribeui/wiki/Getting-started-with-ScribeUI) page, so as the last week is there, I'd suggest you update it to incorporate the import, the classify, the new WMS url, etc.

**Comment by samuellapointe** [comment]
Updated: https://github.com/mapgears/scribeui/wiki/Getting-started-with-ScribeUI

**Comment by jlap** [comment]
That's great thanks !
