### ISSUE TITLE
Installing behind a corporate proxy

### ISSUE THREAD

**Issue by fredmorin** [mapgears/scribeui#141]
I am trying to setup ScribeUI, unfortunatly I am behind a corporate proxy. 

I am following the installation instruction : http://mapgears.github.io/scribeui/installation.html and running the make install command fails to download dependencies.

I generally install python dependencies : pip --proxy=http://localhost:3182 install "dependency-name"

I modified the Makefile to download all the dependencies specified in requirements.txt, but I now end up with another issue when it tries to install/download GeoAlchemy2==0.2 .

Is there a way to specify the proxy when calling make install or to make the Makefile support http_proxy environment variable?

**Comment by jlarouche** [comment]
Please try to set the `HTTP_PROXY` environment variable to your proxy. The makefile is a bit messed up currently and there's some deps installed directly by PIP and some by Distutil using Setup.py, this is the case for GeoAlchemy.

Since it's using easy_install, the `HTTP_PROXY` env variable should be enough.

**Comment by fredmorin** [comment]
I configured the HTTP_PROXY correctly and made changes to line 76 to specify the --proxy option. Still failed. I removed the -q (quiet) parameter and found. It is now able to install all the requirements except for GDAL which fails to install with fatal error cpl_port.h: No such file or directory.

**Comment by fredmorin** [comment]
I finally was able to install all the dependencies, had to install python-gdal from the ubuntugis repository. ppa:ubuntugis/ubuntugis-unstable

http://gis.stackexchange.com/questions/28966/python-gdal-package-missing-header-file-when-installing-via-pip
