### ISSUE TITLE
Problem writing Layer OPACITY with scale rules in COMPOSITE block

### ISSUE THREAD

**Issue by LarsSchy** [mapgears/scribeui#143]
The following syntax gives errors in ScibeUI.  I think it should work.  COMPOSITE also seems to be a missing keyword since it is not colored in pink.

        COMPOSITE {
            13 -14 {
    		OPACITY: 60
            }
            15-16 {
                OPACITY: 100
            }
        }

**Comment by samuellapointe** [comment]
There's a space between 13 and -14. Try this:
```
COMPOSITE {
        13-14 {
            OPACITY: 60
        }
        15-16 {
            OPACITY: 100
        }
    }
```

**Comment by LarsSchy** [comment]
Those little spaces are hard to find sometimes.  Thanks!
